spring.application.name=codeCollabBackend

# Database configuration

spring.mongodb.uri=mongodb://localhost:27017/codeCollabDB

judge0.api.key=fdee1d71e7mshd4a9b7c5098386cp1d830ajsnb6c957875966

#Security
